name: Publish to GitHub Packages

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    uses: Jeremy27/LammCI/.github/workflows/library-release.yml@main
    permissions:
      contents: read
      packages: write
